-- SAMAQU Keyboard — Supabase setup for the Auto Text backend.
--
-- The keyboard syncs chat templates from two tables that the store website does not use,
-- so they live under their own names with read-only public access:
--   categories (id, name) 1--n templates (id, category_id, content)
-- PostgREST then serves `categories?select=id,name,templates(id,content)` as one nested payload.
--
-- Safe to re-run: every statement is idempotent.

create table if not exists public.categories (
    id            bigint generated by default as identity primary key,
    name          text        not null,
    display_order integer     not null default 0,
    created_at    timestamptz not null default now()
);

create table if not exists public.templates (
    id            bigint generated by default as identity primary key,
    category_id   bigint      not null references public.categories (id) on delete cascade,
    content       text        not null,
    display_order integer     not null default 0,
    created_at    timestamptz not null default now()
);

create index if not exists templates_category_id_idx on public.templates (category_id);

-- Read-only for the anon key that ships inside the app; no write access at all.
alter table public.categories enable row level security;
alter table public.templates  enable row level security;

grant select on public.categories to anon, authenticated;
grant select on public.templates  to anon, authenticated;

drop policy if exists "categories are publicly readable" on public.categories;
create policy "categories are publicly readable"
    on public.categories for select to anon, authenticated using (true);

drop policy if exists "templates are publicly readable" on public.templates;
create policy "templates are publicly readable"
    on public.templates for select to anon, authenticated using (true);

-- ------------------------------------------------------------------ seed data
-- The dashboard inside the keyboard edits these two tables, so unlike `orders` and
-- `products` they also need write grants. They hold canned replies only, no customer data.
grant insert, update, delete on public.categories to anon, authenticated;
grant insert, update, delete on public.templates  to anon, authenticated;

drop policy if exists "categories are writable by the app" on public.categories;
create policy "categories are writable by the app"
    on public.categories for insert to anon, authenticated with check (true);

drop policy if exists "categories are updatable by the app" on public.categories;
create policy "categories are updatable by the app"
    on public.categories for update to anon, authenticated using (true) with check (true);

drop policy if exists "categories are deletable by the app" on public.categories;
create policy "categories are deletable by the app"
    on public.categories for delete to anon, authenticated using (true);

drop policy if exists "templates are writable by the app" on public.templates;
create policy "templates are writable by the app"
    on public.templates for insert to anon, authenticated with check (true);

drop policy if exists "templates are updatable by the app" on public.templates;
create policy "templates are updatable by the app"
    on public.templates for update to anon, authenticated using (true) with check (true);

drop policy if exists "templates are deletable by the app" on public.templates;
create policy "templates are deletable by the app"
    on public.templates for delete to anon, authenticated using (true);

insert into public.categories (name, display_order)
select v.name, v.display_order
from (values ('Sapaan', 1), ('Order', 2), ('Pengiriman', 3), ('Penutup', 4))
     as v(name, display_order)
where not exists (select 1 from public.categories);

insert into public.templates (category_id, content, display_order)
select c.id, v.content, v.display_order
from (values
    ('Sapaan',     'Halo Kak 😊 Ada yang bisa kami bantu?', 1),
    ('Sapaan',     'Terima kasih sudah menghubungi SAMAQU 🙏', 2),
    ('Order',      'Pesanan sudah kami terima ya kak. Mohon kirim bukti transfer agar segera kami proses.', 1),
    ('Order',      'Stok masih tersedia kak, silakan lanjut order ya 😊', 2),
    ('Pengiriman', 'Pesanan akan dikirim hari ini. Estimasi 2-4 hari kerja ya kak 🚚', 1),
    ('Pengiriman', 'Nomor resi sudah kami update ya kak, silakan dicek 📦', 2),
    ('Penutup',    'Ditunggu order berikutnya ya kak 🙏 Terima kasih!', 1),
    ('Penutup',    'Jika ada kendala, jangan ragu chat kami ya kak 💬', 2)
) as v(category, content, display_order)
join public.categories c on c.name = v.category
where not exists (select 1 from public.templates);

-- PostgREST caches the schema; ask it to pick the new tables up straight away.
notify pgrst, 'reload schema';
